trigger:
  - master

pool: Azure Pipelines

jobs:
- job: build
  displayName: 'Build'
  steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'build'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      jdkArchitectureOption: 'x64'
      mavenOptions: '-Xmx1024m'
      sonarQubeRunAnalysis: false
      sqMavenPluginVersionChoice: 'latest' # Required when sonarQubeRunAnalysis == True# Options: latest, pom