trigger:
  - master

pool: Azure Pipelines

jobs:
- job: build
  displayName: 'Build'
  steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'package'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      jdkArchitectureOption: 'x64'
      mavenOptions: '-Xmx1024m'
      sonarQubeRunAnalysis: false
      sqMavenPluginVersionChoice: 'latest' # Required when sonarQubeRunAnalysis == True# Options: latest, pom
  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)'
      contents: |
        **/build/libs/spring-boot-kubernetes-*.jar
      targetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: appJar
      publishLocation: 'Container'
      
- job: sonar
  workspace:
    clean: all
  displayName:  Code Review
  steps:
  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'Custom-SonarServiceConnection'
      organization: 'key-organization-sonarcloud'
      projectKey: 'famaturanai_spring-boot-kubernetes'
      projectName: 'spring-boot-kubernetes'
    displayName: 'Preparing Sonarqube Environment'

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'package'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      jdkArchitectureOption: 'x64'
      mavenOptions: '-Xmx1024m'
      sonarQubeRunAnalysis: true
      sqMavenPluginVersionChoice: 'latest' # Required when sonarQubeRunAnalysis == True# Options: latest, pom
    displayName: 'Analyze current Branch'

  - task: SonarCloudPublish@1
    inputs:
      pollingTimeoutSec: '300'
    displayName: 'Publish Analysis Results'

  - task: sonarcloud-buildbreaker@2
    inputs:
      SonarCloud: 'Custom-SonarServiceConnection'
      organization: 'famaturanai'