trigger:
  - master

pool: Azure Pipelines

jobs:
- job: build
  displayName: 'Build'
  steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      #goals: 'package'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      mavenVersionOption: 'Default'
      jdkArchitectureOption: 'x64'
      mavenOptions: '-Xmx1024m'
      effectivePomSkip: false
      sonarQubeRunAnalysis: false
  
  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)'
      contents: |
        **/build/libs/spring-boot-kubernetes-*.jar
      targetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PowerShell@2
    displayName: Display SourcesDirectory
    inputs:
      targetType: 'inline'
      script: 'Write-Host "Version of app ---> [$(Build.SourcesDirectory)]"' # prints empty

  - task: PowerShell@2
    displayName: Display SourcesDirectory
    inputs:
      script: 'Write-Host " $(Build.SourcesDirectory)' # prints empty

  - pwsh: Get-ChildItem *.* -Recurse -Path $(Pipeline.Workspace) | Select-Object UnixMode, Length, Name
    displayName: 'Show folder contents for debugging'
      
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: appJar
      publishLocation: 'Container'

- job: horusec
  workspace:
    clean: all
  displayName: Horusec
  steps:
    - script: |
        curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest
        horusec start -p ./src  
              
- job: sonar
  workspace:
    clean: all
  displayName:  Code Review
  steps:
  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'Custom-SonarServiceConnection'
      organization: 'famaturanai'
      projectKey: 'famaturanai_spring-boot-kubernetes'
      projectName: 'spring-boot-kubernetes'
    displayName: 'Preparing Sonarqube Environment'

  #- task: Maven@3
  #  inputs:
  #    mavenPomFile: 'pom.xml'
  #    goals: 'package'
  #    javaHomeOption: 'JDKVersion'
  #    jdkVersionOption: '1.11'
  #    jdkArchitectureOption: 'x64'
  #    mavenOptions: '-Xmx1024m'
  #    sonarQubeRunAnalysis: true
  #    sqMavenPluginVersionChoice: 'latest' # Required when sonarQubeRunAnalysis == True# Options: latest, pom
  #  displayName: 'Analyze current Branch'

  - task: Maven@3    
    inputs:
      mavenPomFile: 'pom.xml'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: true
      sqMavenPluginVersionChoice: 'latest'
      checkStyleRunAnalysis: true
      pmdRunAnalysis: true
      findBugsRunAnalysis: true

  - task: SonarCloudPublish@1
    inputs:
      pollingTimeoutSec: '300'
    displayName: 'Publish Analysis Results'

  - task: sonarcloud-buildbreaker@2
    inputs:
      SonarCloud: 'Custom-SonarServiceConnection'
      organization: 'famaturanai'

- job: sca
  steps:
  - task: dependency-check-build-task@6
    inputs:
      projectName: 'spring-boot-kubernetes'
      #scanPath: '$(Pipeline.Workspace)'
      #scanPath: ' **/build/libs/spring-boot-kubernetes-*.jar'
      scanPath: '$(Build.SourcesDirectory)/**/*.*'
      failOnCVSS: 8 # Fail the build if vulnerabilities with CVSS score higher than 8 are discovered
      format: 'HTML'
      enableVerbose: true
      enableExperimental: true # Enable experimental file type analyzers
      additionalArguments: '--scan $(Pipeline.Workspace)/**/*.*' # Additional folder to scan
      #dependencyCheckVersion: '6.1.6'
    displayName: 'OWASP Dependency Check scan of third-party dependencies' # This task will perform security scan of third-party dependencies

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: 'dependency-check/*junit.xml'
      searchFolder: '$(Common.TestResultsDirectory)'
      testRunTitle: 'Dependency Check'
      buildConfiguration: '$(BuildConfiguration)'
    displayName: 'Publish OWASP Dependency Check security scan results'