trigger:
  - master

pool: Azure Pipelines

stages:
- stage: Build 
  jobs:
  - job: build
    displayName: 'Build'
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'package'
        publishJUnitResults: false 
        testResultsFiles: '**/surefire-reports/TEST-*.xml' # Required when publishJUnitResults == True
        testRunTitle: 'TEST0-Example'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.11'
        mavenVersionOption: 'Default'
        jdkArchitectureOption: 'x64'
        mavenOptions: '-Xmx1024m'
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
    
    - task: CopyFiles@2
      inputs:
        sourceFolder: '$(Build.SourcesDirectory)'
        contents: |
          **/target/spring-boot-kubernetes-*.jar
        targetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: app
        publishLocation: 'Container'

- stage: DependencyCheck
  jobs:
  - job: sca
    displayName: 'DependencyCheckBuild'
    steps:
    - task: dependency-check-build-task@6
      inputs:
        projectName: 'spring-boot-kubernetes'
        ##scanPath: '$(Build.ArtifactStagingDirectory)/**/*.jar'
        scanPath: '/home/vsts/work/**/*.jar'
        failOnCVSS: 0 # Fail the build if vulnerabilities with CVSS score higher than 8 are discovered
        format: 'HTML'
        enableVerbose: false
        ##enableExperimental: true # Enable experimental file type analyzers
        ##additionalArguments: '--scan $(Pipeline.Workspace)/**/*.*' # Additional folder to scan
        ##dependencyCheckVersion: '6.1.6'
      displayName: 'OWASP Dependency Check scan of third-party dependencies' # This task will perform security scan of third-party dependencies

- stage: Test 
  jobs:            
  - job: sonar
    workspace:
      clean: all
    displayName: Code Review
    steps:
    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'Custom-SonarServiceConnection'
        organization: 'famaturanai'
        projectKey: 'famaturanai_spring-boot-kubernetes'
        projectName: 'spring-boot-kubernetes'
      displayName: 'Preparing Sonarqube Environment'

    - task: Maven@3    
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: false 
        testResultsFiles: '**/surefire-reports/TEST-*.xml' # Required when publishJUnitResults == True
        testRunTitle: 'TEST-Example'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.11'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: true
        sqMavenPluginVersionChoice: 'latest'
        checkStyleRunAnalysis: true
        pmdRunAnalysis: true
        findBugsRunAnalysis: true

    - task: SonarCloudPublish@1
      inputs:
        pollingTimeoutSec: '300'
      displayName: 'Publish Analysis Results'
    - task: sonarcloud-buildbreaker@2
      inputs:
        SonarCloud: 'Custom-SonarServiceConnection'
        organization: 'famaturanai'

- stage: End
  jobs:
  - job: print
    displayName: 'Print'
    steps:
    - task: PowerShell@2
      displayName: message
      inputs:
        targetType: 'inline'
        script: 'Write-Host "Executed successfully"'