trigger:
  - master

pool: Azure Pipelines

stages:
- stage: Build 
  jobs:
  - job: build
    displayName: 'Build'
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'package'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.11'
        mavenVersionOption: 'Default'
        jdkArchitectureOption: 'x64'
        mavenOptions: '-Xmx1024m'
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
